spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: cos
    password: cos1234
    url: jdbc:mariadb://localhost:3306/cosdb?serverTimezone=Asia/seoul
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
